### ISSUE TITLE
Uncaught RuntimeError: wrapped C/C++ object of type landsurveyAlgorithm has been deleted


### ISSUE THREAD

**Issue by areithofer** [Oslandia/landsurveycodesimport#11]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LandSurveyCodesImport\land_survey_provider.py", line 56, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type landsurveyAlgorithm has been deleted

```
LandSurveyCodesImport 0.1, QGIS 3.8.0-Zanzibar on Windows 10

**Comment by lbartoletti** [comment]
Thanks @zoran2k 

You can test this patch by replacing the file land_survey_provider.py by [this one](https://raw.githubusercontent.com/Oslandia/landsurveycodesimport/1cb25dfb8f5f9a9a011a6c9efce83f001994010d/land_survey_provider.py)

**Comment by lbartoletti** [comment]
@zoran2k A new version is available https://github.com/Oslandia/landsurveycodesimport/releases/tag/v0.1.1 and it will be available (awaiting approval) on http://plugins.qgis.org/plugins/LandSurveyCodesImport/ soon
